### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli#29]
(copied from `README.md` since it belongs outside the source)

## Features & v1.0 Roadmap

-   [x] Heirarchical command namespaces (`d2`, `d2 app`, `d2 app scripts` etc.)
-   [x] Programmatic and command-line entrypoints at any command level
-   Configurability through:
    -   [x] command-line (`--verbose=true`)
    -   [x] custom file (`--config=.myd2rc`)
    -   [x] package.json (`"d2": { "verbose": true }`)
    -   [x] environment variables (`D2_VERBOSE=true`)
    -   [ ] find-up .rc files
    -   [ ] globally-installed user config (`~/.config/d2` or `~/.cache/d2`)
-   [ ] more performant config/cache initialization (they currently cause a slight startup lag)
-   [ ] Namespaced configuration (i.e. { config: { verbose: true } } instead of { verbose: true }
-   [x] A user-level file cache (located at `~/.cache/d2`) and abstract caching mechanism for use in various commands.
-   [x] Meta/debug command namespace for:
    -   Cache inspection `d2 debug cache`, i.e. `d2 debug cache list`
    -   Config printing `d2 debug config`
    -   System diagnostics `d2 debug system`
-   [x] Automatic update checks with [update-notifier](https://npmjs.com/package/update-notifier) (updates checked at most 1x per day)
-   [x] Basic DHIS2 Docker cluster management with `d2 cluster`
-   [x] Incorporate [packages](https://github.com/dhis2/packages) as a command module
    -   [x] Link to updated [packages](https://github.com/dhis2/packages) using cli engine
    -   [x] Deprecate `d2 package` ?
-   [x] Implement `d2-app-scripts` for application creation (WIP [app-platform](https://github.com/amcgee/dhis2-app-platform)
-   [x] Implement top-level `create` command for bootstrapping `cli`, `app`, and other components
-   [x] Integrate the legacy [`dhis2-cli`](https://www.npmjs.com/package/dhis2-cli) UUID generation functionality ([source](https://github.com/dhis2/dhis2-cli))
-   Implement
    -   [ ] unit tests
    -   [ ] integration / smoke tests
    -   [x] `code-style`
        -   [x] Switch to verb-form command
    -   [x] `commit-style`
        -   [x] Switch to verb-form command
    -   [x] Travis CI
        -   [x] CI deploy to NPM
-   [ ] Build standalone packaged executables with [rollup](https://rollupjs.org/) or [pkg](https://www.npmjs.com/package/pkg)
-   [ ] Add individual package READMEs for better NPM optics
    -   [ ] d2-app
    -   [x] d2-cluster
    -   [ ] d2-create
    -   [ ] d2-utils
-   [ ] Consolidate `makeEntryPoint` and `notifyOfUpdates` since it's boilderplate code.
-   [ ] Handle rejected promises at command level (incorporate `exitOnCatch` helper)
-   [x] Confirm Greenkeeper functionality (add greenkeeper.json for monorepo awareness)
-   [x] Confirm that update notifications work well
-   [x] Cut version 1.0 with baseline feature set and semantic versioning guarantee

### Bonus features

-   [x] Consider mono-repo or poly-repo for code sharing (particularly sharing `cliUtils`)
-   [ ] Consider using typescript for better static analysis

**Comment by amcgee** [comment]
Closing this since most everything is done or superceded.
